import {mkdir,readdir,readFile,writeFile,cp,rm} from 'node:fs/promises';
import path from 'node:path';
const ROOT=path.resolve('.'), OUT=path.join(ROOT,'dist'), BASE='https://xshawalx.github.io/prompts/';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const jsonSafe=o=>JSON.stringify(o).replace(/</g,'\\u003c');
const fmt=d=>new Intl.DateTimeFormat('en',{month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${d}T00:00:00Z`));
await rm(OUT,{recursive:true,force:true}); await mkdir(OUT,{recursive:true});
const contentDir=path.join(ROOT,'content/prompts');
const files=(await readdir(contentDir)).filter(x=>x.endsWith('.json')).sort();
const prompts=[]; for(const f of files) prompts.push(JSON.parse(await readFile(path.join(contentDir,f),'utf8')));
function score(a,b){let s=0;if(a.category===b.category)s+=4;const tags=new Set(a.tags||[]);for(const t of b.tags||[])if(tags.has(t))s+=2;return s;}
function related(p){const explicit=(p.relatedSlugs||[]).map(s=>prompts.find(x=>x.slug===s)).filter(Boolean);const rest=prompts.filter(x=>x.slug!==p.slug&&!explicit.some(e=>e.slug===x.slug)).map(x=>({x,s:score(p,x)})).filter(o=>o.s>0).sort((a,b)=>b.s-a.s).map(o=>o.x);return [...explicit,...rest].slice(0,3);}
function head({title,description,url,ogType='website'}){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#000000"><link rel="canonical" href="${url}"><meta property="og:type" content="${ogType}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><link rel="stylesheet" href="/prompts/assets/css/styles.css">`}
const header=`<body><header class="site-header"><div class="shell header-inner"><a class="brand" href="/prompts/"><span>SHAWAL</span><small>PROMPTS</small></a><nav class="header-links" aria-label="Primary"><a class="text-link" href="/">Homepage</a><a class="text-link" href="/ugc/">UGC</a><a class="button button-primary" href="/prompts/">Prompt Library</a></nav></div></header>`;
const footer=`<footer class="site-footer"><div class="shell footer-inner"><span>XSHAWALX Prompt Library</span><span>Orange #FF6A00 · Black #000000</span></div></footer>`;
const indexMeta=prompts.map(({prompt,fields,howToUse,relatedSlugs,...m})=>m);
const categories=[...new Set(prompts.map(p=>p.category))];
const home=`${head({title:'AI Prompt Library | Shawal',description:'Useful AI master prompts you can customize, copy and use.',url:BASE})}<script type="application/ld+json">${jsonSafe({'@context':'https://schema.org','@type':'WebSite',name:'Shawal AI Prompt Library',url:BASE,author:{'@type':'Person',name:'Shawal'}})}</script></head>${header}<main><section class="hero shell"><p class="eyebrow">XSHAWALX PUBLIC AI PROMPT LIBRARY</p><h1>Prompt Library</h1><p class="hero-copy">Useful AI master prompts you can customize, copy and use.</p><div class="toolbar"><label class="sr-only" for="prompt-search">Search prompts</label><input class="input" id="prompt-search" type="search" placeholder="Search by title, category, tag, use case…" autocomplete="off"><a class="button button-primary" href="#all-prompts">Browse all</a></div></section><section class="section shell" aria-labelledby="featured-title"><div class="section-head"><div><p class="eyebrow">CURATED</p><h2 id="featured-title">Featured Prompts</h2></div><p>Featured is manually curated for V1. No fake popularity or usage counts.</p></div><div class="grid" id="featured-grid"></div></section><section class="section shell" aria-labelledby="categories-title"><div class="section-head"><div><p class="eyebrow">EXPLORE</p><h2 id="categories-title">Categories</h2></div><p>Only categories containing real published prompts are shown.</p></div><div class="chip-row" id="category-row" aria-label="Prompt categories"></div></section><section class="section shell" id="all-prompts" aria-labelledby="all-title"><div class="section-head"><div><p class="eyebrow" id="result-count">${prompts.length} prompts</p><h2 id="all-title">All Prompts</h2></div><p>Find → Customize → Preview → Copy → Open ChatGPT</p></div><div class="grid" id="all-grid"></div></section></main>${footer}<script src="/prompts/assets/js/library.js" defer></script></body></html>`;
await writeFile(path.join(OUT,'index.html'),home);
await mkdir(path.join(OUT,'data'),{recursive:true}); await writeFile(path.join(OUT,'data/prompts-index.json'),JSON.stringify(indexMeta,null,2));
for(const p of prompts){
  const rel=related(p); const url=`${BASE}${p.slug}/`; const title=`${p.title} | Shawal`;
  const breadcrumbs={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Prompt Library',item:BASE},{'@type':'ListItem',position:2,name:p.title,item:url}]};
  const creative={'@context':'https://schema.org','@type':'CreativeWork',name:p.title,description:p.description,url,author:{'@type':'Person',name:'Shawal'},dateModified:p.updatedAt,version:p.version,keywords:p.tags||[]};
  const formPanel=(p.fields||[]).length?`<section class="panel"><h2>Customize</h2><div class="form-grid" id="form-grid"></div><div class="form-actions"><button class="button button-secondary" id="reset-prompt" type="button">Reset</button></div><p class="support-copy">Your entries stay in this browser. They are not uploaded or sent to analytics.</p></section>`:`<section class="panel"><h2>Ready to use</h2><div class="form-grid" id="form-grid"></div></section>`;
  const how=(p.howToUse?.length)?`<section class="howto shell"><p class="eyebrow">HOW TO USE</p><h2>Use it in four steps</h2><ol>${p.howToUse.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section>`:'';
  const relatedHtml=rel.length?`<section class="related shell"><div class="section-head"><div><p class="eyebrow">NEXT</p><h2>Related Prompts</h2></div></div><div class="grid">${rel.map(x=>`<article class="card"><div class="badges"><span class="badge">${esc(x.category)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><a class="button button-secondary" href="/prompts/${esc(x.slug)}/">Open Prompt</a></article>`).join('')}</div></section>`:'';
  const page=`${head({title,description:p.description,url,ogType:'article'})}<script type="application/ld+json">${jsonSafe(breadcrumbs)}</script><script type="application/ld+json">${jsonSafe(creative)}</script></head>${header}<main><section class="prompt-hero shell"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/prompts/">Prompt Library</a><span aria-hidden="true">/</span><span>${esc(p.category)}</span></nav><div class="badges"><span class="badge">${esc(p.category)}</span>${p.featured?'<span class="badge badge-solid">Featured</span>':''}${p.isNew?'<span class="badge">New</span>':''}</div><h1 class="prompt-title">${esc(p.title)}</h1><p class="prompt-intro">${esc(p.description)}</p><div class="meta-row"><span>Who it’s for: ${esc(p.audience)}</span><span>Version ${esc(p.version)}</span><span>Updated ${esc(fmt(p.updatedAt))}</span></div></section><section class="shell detail-grid">${formPanel}<section class="panel preview-wrap"><h2>Live Master Prompt</h2><div class="preview-actions"><button class="button button-primary" id="copy-prompt" type="button">Copy Prompt</button><a class="button button-secondary" id="open-chatgpt" href="https://chatgpt.com/" target="_blank" rel="noopener noreferrer">Open ChatGPT</a><button class="button button-quiet" id="share-prompt" type="button">Share Prompt</button></div><pre class="preview" id="prompt-preview" tabindex="0"></pre><p class="support-copy">Required fields must be completed before copying. Optional empty blocks disappear automatically.</p></section></section>${how}${relatedHtml}</main>${footer}<div class="toast" id="toast" role="status" aria-live="polite"></div><script id="prompt-data" type="application/json">${jsonSafe(p)}</script><script src="/prompts/assets/js/prompt.js" defer></script></body></html>`;
  const dir=path.join(OUT,p.slug); await mkdir(dir,{recursive:true}); await writeFile(path.join(dir,'index.html'),page);
}
await cp(path.join(ROOT,'assets'),path.join(OUT,'assets'),{recursive:true});
await writeFile(path.join(OUT,'.nojekyll'),'');
await writeFile(path.join(OUT,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${BASE}sitemap.xml\n`);
const urls=[BASE,...prompts.map(p=>`${BASE}${p.slug}/`)]; await writeFile(path.join(OUT,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${u}</loc></url>`).join('')}</urlset>`);
console.log(`Built ${prompts.length} prompt page(s) into dist/.`);
